### ISSUE TITLE
crashes after wad selection on Linux

### ISSUE THREAD

**Issue by wantija** [ZDoom/gzdoom#1416]
OS: Arch Linux
GPU: RX 580 8GB, Mesa 21.1.3
CPU: R5 2600X

When selecting a wad the menu disappears and the game isn't launched. Terminal prints a very uninformitive log.
`GZDoom g4.6.0-m - 2021-05-22 16:34:22 +0200 - SDL version
Compiled on Jun 16 2021

OS: Arch Linux, Linux 5.12.12-zen1-1-zen on x86_64
M_LoadDefaults: Load system defaults.
^CW_Init: Init WADfiles.
 adding /usr/lib/gzdoom/gzdoom.pk3, 633 lumps
 adding /usr/lib/gzdoom/game_support.pk3, 2514 lumps
 adding /mnt/hdd1/hdd_games/doom_wads/WADS/DOOM2.WAD, 2919 lumps
 adding /usr/share/gzdoom/game_widescreen_gfx.pk3, 98 lumps
I_Init: Setting up machine state.
CPU Vendor ID: AuthenticAMD
  Name: AMD Ryzen 5 2600X Six-Core Processor 
  Family 23 (23), Model 8, Stepping 2
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
[ALSOFT] (EE) Failed to set real-time priority for thread: Operation not permitted (1)
  Opened device Family 17h (Models 00h-0fh) HD Audio Controller Analog Stereo
  EFX enabled
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 121.72 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
illegal environment value for mesa_glthread: "1".  Ignoring.
radeonsi: Forcing anisotropy filter to 16x
Using video driver x11
GL_VENDOR: AMD
GL_RENDERER: Radeon RX 580 Series (POLARIS10, DRM 3.40.0, 5.12.12-zen1-1-zen, LLVM 12.0.0)
GL_VERSION: 4.6 (Core Profile) Mesa 21.1.3 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60

Max. texture size: 16384
Max. texture units: 32
Max. varying: 128
Max. combined shader storage blocks: 80
Max. vertex shader storage blocks: 16
Resolution: 640 x 480`

**Comment by alexey-lysiuk** [comment]
Was `gzdoom-crash.log` created in the current directory? If so, post this file here. If it wasn't, run GZDoom under `gdb` and do `bt` command when it crashes.

**Comment by wantija** [comment]
Looks like launching gzdoom with -iwad /path/to/doom2.wad worked, but the GUI just crashes. 
[gzdoomdebug.log](https://github.com/coelckers/gzdoom/files/6730063/gzdoomdebug.log)
[gzdoomdebug2.log](https://github.com/coelckers/gzdoom/files/6730064/gzdoomdebug2.log)

**Comment by alexey-lysiuk** [comment]
`SIG33` should be ignored, use `c` command to continue execution. If that signal triggers multiple times, do `handle SIG33 pass nostop noprint` to disable its handling.

**Comment by bhbuehler** [comment]
I had a similar issue when I recently built  g4.11pre-222-g62f37079a on Arch (Commit 62f37079a7834b813f251818d1db6c80e644d209) with ZMusic version 1.1.12. It began working soon after and I wasn't able to determine what caused this (I think it was either restarting or installing some missing dependency). I also tried rebuilding to see if I could reproduce the issue I had upon first building. Is there any information I could provide to help solve this?

**Comment by bhbuehler** [comment]
I didn't expect to be commenting again so quickly, but in trying to investigate a different bug, I inadvertently reintroduced this to my build by restoring default settings in the gzdoom menu.


`$ gzdoom -iwad ~/some_directory/some_other_directory/doom2.wad 
GZDoom g4.11pre-222-g62f37079a - 2023-07-22 13:22:53 +0300 - SDL version
Compiled on Jul 30 2023

OS: Arch Linux, Linux 6.4.7-arch1-1 on x86_64
GZDoom version g4.11pre-222-g62f37079a
W_Init: Init WADfiles.
 adding /usr/local/share/games/doom/gzdoom.pk3, 672 lumps
 adding /usr/local/share/games/doom/game_support.pk3, 3307 lumps
 adding /home/bhbuehler/Games/doom2/doom2.wad, 2919 lumps
 adding /usr/local/share/games/doom/game_widescreen_gfx.pk3, 214 lumps
S_Init: Setting up sound.
I_InitSound: Initializing OpenAL
  Opened device Built-in Audio Analog Stereo
  EFX enabled
I_Init: Setting up machine state.
CPU speed: 3418 MHz
CPU Vendor ID: GenuineIntel
  Name: 13th Gen Intel(R) Core(TM) i7-13700K
  Family 6, Model 183, Stepping 1
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 F16C FMA3 BMI1 BMI2 HyperThreading
V_Init: allocate screen.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
script parsing took 142.73 ms
R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Using video driver x11
GL_VENDOR: AMD
GL_RENDERER: AMD Radeon RX 5500 XT (navi14, LLVM 15.0.7, DRM 3.52, 6.4.7-arch1-1)
GL_VERSION: 4.6 (Core Profile) Mesa 23.1.5 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.60

Max. texture size: 16384
Max. texture units: 32
Max. varying: 128
Max. combined shader storage blocks: 80
Max. vertex shader storage blocks: 16
Resolution: 640 x 480
Killed================================================================================================================================================================================.......]`

After some investigation, I found **the game works iff vid_preferbackend is set to 1 in the ini file**. Changing the rendering device to vulkan on the iwad selector dialog box appears to indirectly solve this issue as well by changing the vid_preferbackend setting (strangely, for me the option did not appear in the selector unless sending the ^C signal in the terminal running the program upon which the dialog box changes appearence and has additional options) . However, changing the rendering device to vulkan manually in the config file (vid_rendermode=4) did NOT fix the issue.

This may not be the issue @wantija has (for example, I am unable to launch gzdoom with default settings regardless of whether I select the iwad on the command line or gui selector), but it is quite similar and seems like it might have been the initial issue (inadvertently fixed by changing the rendering device as described above) and seems like it would be worth asking @wantjia or someone else with arch to see if they could reproduce it by 

1. saving their working ini file manually (the in-game configuration save does not appear to save it),
2. setting their configuration to default,
3. checking to see if the game doesn't launch, and then
4. checking to see if the game does launch after changing vid_preferbackend to 1
(or by following just step 4 if their copy doesn't work).
