### ISSUE TITLE
[BUG] macOS random lock-ups on gzDoom 4.7.0

### ISSUE THREAD

**Issue by rtpHarry** [ZDoom/gzdoom#1489]
### GZDoom version

4.7.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Mac OS

### Relevant hardware info

Big sur 11.5.2

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

So this is a bit of a hard to detect one here, I guess. I just updated to the latest v4.7.0, I was on v4.5.0.

I have gfxCardStatus installed and I use that to force the discrete graphics card, rather than the integrated.

When I'm playing doom with this version it will randomly freeze. If I cmd+tab out of the display and return then it instantly resumes play.

The game is "paused" while it's happening - if a monster is attacking me, then I'm not dead when I return from it being frozen. It instantly restarts when I return, so it not paused as in game paused / in the menu, but it's not just the display thats frozen, the entire game has stopped.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Playing the game normally, don't have a specific repro

### Provide a Log

No crash

**Comment by Gaerzi** [comment]
The game automatically pauses when it loses focus. Maybe what's happening here is that the game thinks it has lost focus when it hasn't? What about the sounds and music, do they stop too during these freezes?

**Comment by rtpHarry** [comment]
Yes it seems to be a full stop. I don't have music turned on, which would make it easier to tell, but the game seems to be just frozen, no sound, and the mouse / input stops working, until I switch out and back in to the window.

So it might be some app that's stealing focus then?

I wonder if the window management changed between 4.5.0 and 4.7.0 that would allow something to interject. I'm trying to think and I don't think I've installed anything new recently. So even if it is an app that's causing it, it seems that something has changed in gzdoom thats now allowing it.

**Comment by rtpHarry** [comment]
The experiments continue. 

On 4.7.0, `vid_nativefullscreen` was false changed it to true. Still happened in that session. Wasn't sure if it needed a reload of the app, but the next session I checked it was still true, and it still happened. 

Will try 4.6.x next.

**Comment by kaosagnt** [comment]
I'm seeing similar things with 4.7.1. 
When the game locks up I just hit the esc key a couple of times and continue playing.
At times the desktop will flash and the game will continue other times we go back to the desktop and have to click on the game in the dock to continue playing.

Happens on both
macOS 11.6.1 big sur
macOS 10.14.x mojave

Both machines are MacBook Pro late 2013
The Big Sur MacBook Pro also has NVIDIA GeForce GT 750M in addition to the Intel Iris Pro 1536 MB

I've only tested running in fullscreen mode.

Will do some further follow up tests shortly.

**Comment by rtpHarry** [comment]
I've been playing on v4.6.1 for several weeks now and not experienced the bug.

I switched back to 4.7.0 briefly and experienced it again.

**Comment by MajorCooke** [comment]
Try 4.7.1?

**Comment by alexey-lysiuk** [comment]
Does it happen in windowed mode? What's the rendering backend (OpenGL/Vulkan/...)? What's the hardware?

**Comment by kaosagnt** [comment]
I've been using 4.6.1 since the 16 Nov and locks happen when using the chaingun on 4.6.1. The lockup allows action to continue, but you have no movement or ability to fire back. Chaingun is the only weapon this happens with on 4.6.1.

Model Name:	MacBook Pro
  Model Identifier:	MacBookPro11,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.3 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	6 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  System Firmware Version:	153.0.0.0.0
  SMC Version (system):	2.19f12

Chipset Model:	Intel Iris Pro
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x0d26
  Revision ID:	0x0008
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal Family:	Supported, Metal GPUFamily macOS 1
  Displays:
Colour LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	2880 x 1800 Retina
  Framebuffer Depth:	24-Bit Colour (ARGB8888)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal

NVIDIA GeForce GT 750M:

  Chipset Model:	NVIDIA GeForce GT 750M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x8
  VRAM (Total):	2 GB
  Vendor:	NVIDIA (0x10de)
  Device ID:	0x0fe9
  Revision ID:	0x00a2
  ROM Revision:	3776
  Automatic Graphics Switching:	Supported
  gMux Version:	4.0.8 [3.2.8]
  Metal Family:	Supported, Metal GPUFamily macOS 1

4.7.1 is way worse for the lockups and interruptions taking you out of fullscreen and back to finder.
4.6.1 does not take you out of fullscreen and back to finder, just the lockups.

Will try playing for a while in window mode to see if anything is different.

**Comment by alexey-lysiuk** [comment]
Initially, I thought about a system-wide keyboard shortcut that is stealing window focus.
However, I have no idea how it relates to the version of GZDoom, and to the chaingun in particular.

**Comment by rtpHarry** [comment]
It sounds like @kaosagnt is experiencing a different bug to the one I originally reported. 

This thread is about 4.7.0, not 4.6.1. Moving back to 4.6.1 solves the lockups for me.

The lock up bug that I have reported appears to be the window losing focus for some reason.

The entire game stops/pauses and it doesn't come back until I tab out and in again. 

The game has not progressed while it was frozen or while I was tabbed out of the screen.

**Comment by rtpHarry** [comment]
> Does it happen in windowed mode? What's the rendering backend (OpenGL/Vulkan/...)? What's the hardware?

how can I get a hardware dump like @kaosagnt posted?

It is:

Rendering: Vulcan
Render Mode: Hardware Accelerated
Fullscreen: Yes
Retina: No

**Comment by alexey-lysiuk** [comment]
> how can I get a hardware dump like @kaosagnt posted?

It's from System Information app, copied from Hardware and Graphics/Displays pages.

> Rendering: Vulcan Render Mode:

First of all, try in windowed mode. If it won't change anything, switch to OpenGL, and restart GZDoom. Also, you can try with integrated graphics as well.

**Comment by rtpHarry** [comment]
```
Hardware Overview:

  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro16,1
  Processor Name:	8-Core Intel Core i9
  Processor Speed:	2.4 GHz
  Number of Processors:	1
  Total Number of Cores:	8
  L2 Cache (per Core):	256 KB
  L3 Cache:	16 MB
  Hyper-Threading Technology:	Enabled
  Memory:	32 GB
  System Firmware Version:	1715.40.15.0.0 (iBridge: 19.16.10549.0.0,0)
  OS Loader Version:	540.40.4~45
  Serial Number (system):	C02ZVAYZMD6T
  Hardware UUID:	C3E6DBC6-D955-5D99-BAC7-551C982F1806
  Provisioning UDID:	C3E6DBC6-D955-5D99-BAC7-551C982F1806
  Activation Lock Status:	Enabled

AMD Radeon Pro 5500M:

  Chipset Model:	AMD Radeon Pro 5500M
  Type:	GPU
  Bus:	PCIe
  PCIe Lane Width:	x16
  VRAM (Total):	8 GB
  Vendor:	AMD (0x1002)
  Device ID:	0x7340
  Revision ID:	0x0040
  ROM Revision:	113-D3220E-190
  VBIOS Version:	113-D32206U1-019
  Option ROM Version:	113-D32206U1-019
  EFI Driver Version:	01.A1.190
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Family:	Supported, Metal GPUFamily macOS 2

Intel UHD Graphics 630:

  Chipset Model:	Intel UHD Graphics 630
  Type:	GPU
  Bus:	Built-In
  VRAM (Dynamic, Max):	1536 MB
  Vendor:	Intel
  Device ID:	0x3e9b
  Revision ID:	0x0002
  Automatic Graphics Switching:	Supported
  gMux Version:	5.0.0
  Metal Family:	Supported, Metal GPUFamily macOS 2
  Displays:

Colour LCD:
  Display Type:	Built-In Retina LCD
  Resolution:	3072x1920 Retina
  Framebuffer Depth:	30-Bit Colour (ARGB2101010)
  Main Display:	Yes
  Mirror:	Off
  Online:	Yes
  Automatically Adjust Brightness:	Yes
  Connection Type:	Internal
```

I will start working through the combinations and come back to you over the next few weeks.

**Comment by rtpHarry** [comment]
By default, gzdoom won't request the discrete card when its load, it just uses whatever is active.

This took me a long time to realise, and I wondered why sometimes I was getting silky smooth gameplay and sometimes it would chug. 

It turned out it was when I had Photoshop open, which forces discrete.

I have an app called gfxCardStatus which lets me toggle the active card.

I mostly play on discrete now unless I forget, but I will also track if this makes a difference.

**Comment by kaosagnt** [comment]
A bit more on what I am seeing. Went back to 4.7.1 for a bit. Set vulcan mode, apart from choppy frame rate on my hardware, no lock ups seen. Went back to OpenGL and had a lock up again. When the lock up happens, all keys except for the esc key are unresponsive to the game, which is why the game play continues but you cannot respond. pressing esc twice takes you to the menu and then back to the game with the keyboard controls active again. I'd say the same bug is in 4.6.1 or earlier.

The game I am currently playing is Doom 2 hell on earth selected and the
-file "/Applications/Games/WAD Files/eternal/ETERNALL.WAD"
 for eternal doom. I don't think that it is game specific as I have been playing others in the past when this happens.

**Comment by rtpHarry** [comment]
@kaosagnt do you have "rectangle" running on your system? The window screen size management app? 

Because for me, I was playing for months with random kind of lock ups when I was clicking the left mouse button and trying to move around. It would just stick in place in the direction that I was moving, so I couldn't circle strafe or anything.

I realised that when I closed "rectangle" that type of "lock ups" didn't happen any more.

**Comment by kaosagnt** [comment]
@rtpHarry If your referring to this https://rectangleapp.com then no. I have never knowingly installed that app.

kristamari-w1:~>ps agxww | grep -i rect
  108   ??  Ss     0:03.77 /usr/libexec/opendirectoryd
 9119 s000  S+     0:00.00 grep -i rect

What is interesting is that when the lockup happens, if i'm turning to the left / right, I'll go into a spin when the lock up happens like the key becomes stuck.

**Comment by coelckers** [comment]
Closing due to old age
