### ISSUE TITLE
[BUG] Gamepad not working properly on linux

### ISSUE THREAD

**Issue by Espiga5** [ZDoom/gzdoom#1585]
### GZDoom version

4.7.1

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

CPU: AMD A6-7310 with APU Radeon R4, Ram: 4GB

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When a Gamepad is connected (wired Xbox 360 controller in my case) games are getting random inputs even if no touching the gamepad and the only way to play is disconnecting the gamepad. So, the problem is not just not being able to play using gamepad, but if gamepad is connected i can't choose play, options or exit till discconect it. 

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Connect a wired Gamepad
2. Open any game using GZDOOM

**Comment by OrdinaryMagician** [comment]
I've been experiencing this bug for years and it's just a matter of the default axis mappings being incorrect.

A workaround is to disable gamepad input in menus before connecting it, and then remapping the axes. Still, the fact the defaults for this aren't sane because it maps the analog triggers to stuff that should be handled by the sticks is a problem.

But I think that's just part of the design quirk of the gamepad, where internally the axes aren't ordered in a consistent way. It's something along the lines of: "Left Stick X", "Left Stick Y", "Left Trigger", "Right Stick X", "Right Stick Y", "Right Trigger". LT is just stuck in the middle, there, and it screws with the mappings because gzdoom just reads its resting state as "you're holding left on the right analog stick" or something like that. There's also an issue too with drifting because the sticks have no deadzone whatsoever internally, which is why the menu selection goes nuts with it connected too.

The issue also extends to Xbox One gamepads, by the way. All of them are fugged on Linux like that. I don't know why SDL2 doesn't have a system in place to fix that quirk.

**Comment by franzmondlichtmann** [comment]
I have the same problem as the original poster.
A workaround is to switch "Block controller support in menus" in the controller options to YES.
Or set mblockcontrollers=true in the gzdoom.ini

**Comment by coelckers** [comment]
Needs to be looked into with appropriate hardware.
