### ISSUE TITLE
[BUG] Can't compile on Fedora 36 -- Cmake cannot find libvpx

### ISSUE THREAD

**Issue by Bibobu** [ZDoom/gzdoom#1721]
### GZDoom version

Git version

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Fedora 36

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

cmake cannot find the libvpx library that is needed for compilation.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. clone git repository
2. mkdir build && cd build
3. cmake ..

### Your configuration

```ini
The lib is located in /usr/lib64/libvpx.so.7
1) I do not think this link is checked by Cmake (but I am not skilled enough with Cmake to be 100% sure)
2) I think gzdoom might need libvpx.so.6. Am I right about this too?
```

### Provide a Log

https://gist.github.com/Bibobu/072884129b9cae4095c6c7f8439269ef

**Comment by madame-rachelle** [comment]
The problem here is that your distro is not providing an obvious place to look for libvpx that GZDoom is able to actually find.

Please take a look at https://github.com/ZDoom/gzdoom/blob/master/cmake/FindVPX.cmake - search your file system for the relevant files then add them to that file.

If you need examples for how to do this, take a look at https://github.com/ZDoom/gzdoom/blob/master/cmake/FindSDL2.cmake - it has examples on how to add paths to the search.

Once you have fixed this, please feel free to pull request in the relevant changes. As long as they are non-destructive (i.e. they add, not take) then it is likely it will be not only accepted, but appreciated.

**Comment by Cacodemon345** [comment]
I am running Fedora 36, and CMake can find libvpx just fine.

**Comment by madame-rachelle** [comment]
Well - that seems to be a user error, then.

**Comment by Bibobu** [comment]
The error was actually caused by a dependency on `libvpx-devel` which is not listed in the wiki.

**Comment by Gaerzi** [comment]
The wiki compilations instructions are dreadfully in need of cleanup and updating, unfortunately.
