### ISSUE TITLE
[Feature] Rename mancubus actor from Fatso to Mancubus

### ISSUE THREAD

**Issue by mc776** [ZDoom/gzdoom#1760]
### GZDoom version

GZDoom 4.8.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Relevant hardware info

n/a

### Is your feature request related to a problem? Please describe.

Sorry if this seems a bit PC but it does feel awfully fatphobic every time I need to deal with this actor class and am faced with a literal schoolyard taunt.

On a more gamer-codebro-friendly level, though, I honestly have trouble remembering the actor name and am constantly typing `summon mancubus` in the console.

The current name is also way too easy to typo as "Fasto".

### Describe the solution you'd like

Rename the actor from "Fatso" to "Mancubus".

### Describe alternatives you've considered

Freedoom calls it the Combat Slug. It's... not the best name, and not guaranteed to be the same a few years from now.

### Add any other context or screenshots about the feature request here.

https://www.urbandictionary.com/define.php?term=Fatso

**Comment by SanyaWaffles** [comment]
To do this would require a change to all the code involved in existing mods.

**Comment by madame-rachelle** [comment]
Unfortunately it's literally impossible to completely get rid of the "fatso" name. While internally the code can be completely renamed and all existing instances of it completely changed, there would still need a "fatso" reference somewhere that draws from it for backward compatibility in order to not break mods.

Sorry but that's just the way it is. For better or worse "Fatso" has existed in the code now for the better part of 2 decades. Removing the word completely is going to cause massive problems, not because of the massively dumb fuck chuds that absolutely hate PC culture "invading muh pweshus gaemz" (lawl) but there are so many mods that simply depend on the setup that is the way it is.

That being said though - creating a name aliasing feature for ZScript might not be a terrible idea. Being able to actually do renames like this if it is ever needed while allowing aliases to refer to the old names would be very handy for kind of "having your cake and eat it, too" - but this still comes with the caveat that the offensive word itself still has to appear *somewhere*.

**Comment by mc776** [comment]
That kind of aliasing system could still be very useful even if there's no total purge of the word or anything like that! (and it would certainly fully address my own `summon mancubus` use case)

Could also be interesting to allow, say, a different name for an actor depending on whether someone is using id or Freedoom, but maybe that's a bit too far of a stretch (and I can't really think of a good use case for that).

Then again, there's the old `summon imp`/`summon barrel`...

**Comment by coelckers** [comment]
The main issue here is that these names are not just for user input but also engine-side identifiers for inheritance and spawning. So whatever misgivings one might have with Randi's choices from over 20 years ago there is really no way to ever change them again.

An alias list for "summon" is as far as this may ever go.

**Comment by madame-rachelle** [comment]
I don't think it was even solely Randi's choice, either. It was literally named Fatso within the Doom 2 source itself.

https://github.com/id-Software/DOOM/blob/77735c3ff0772609e9c8d29e3ce2ab42ff54d20b/linuxdoom-1.10/info.h#L1172

So you're going to have to chase the id devs about this one. ;)

**Comment by coelckers** [comment]
I'd chase Randi for using these names, despite knowing better. Others have gotten their proper names. For Heretic it was even worse, there nearly all monsters got their informal names attached.
