### ISSUE TITLE
[Feature] Vulkan true/exclusive fullscreen

### ISSUE THREAD

**Issue by dezo2** [ZDoom/gzdoom#1813]
### GZDoom version

GZDoom 4.9.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Relevant hardware info

intel i7-9700, nvidia RTX 3080, monitor 2560x1440 144Hz VRR

### Is your feature request related to a problem? Please describe.

Vulkan renderer is apparently running in windowed fullscreen mode that does not play nice with variable refresh rate monitors.

### Describe the solution you'd like

Could you please add optional true/exclusive fullscreen mode for Vulkan renderer? Variable refresh works just fine with OGL for the whole VRR range (48-144 Hz in my case), so OGL must be using true fullscreen. But with Vulkan there is evident judder when limiting FPS below monitor refresh (GSync is not working). I would like to use Vulkan because it performs much better on large maps that are very CPU limited, which is a problem with OGL.

**Comment by dpjudas** [comment]
There is no difference here between the Vulkan and OpenGL backends - they both use the exact same full screen strategy. I don't know why VRR is working for you in OpenGL and not in Vulkan.

I am currently in the process of changing the backend to use the new ZVulkan library. Once that is done there will be support for vulkan exclusive full screen, but I can't promise exactly when this will happen.

**Comment by dezo2** [comment]
Thanks, looking forward to it.

GZDoom behaves like that for me from the first versions with Vulkan, OGL was always fine. There is a possibility to make it work when I set GSync in NV control panel as "Enable for windowed and fulscreen mode" instead of "Enable for fullscreen mode", but that brings some bugs in windows desktop and some other apps, so I rather don't use that. PS: I don't have this problem in  other source ports using Vulkan (yamagi Quake 2, vkQuake).

**Comment by Calinou** [comment]
Presenting Vulkan over DXGI would likely resolve the issue with VRR not working reliably. With this done, VRR should even work in windowed mode if enabled in the Windows settings.

**Comment by dpjudas** [comment]
While it is certainly true that the vulkan backend could bridge directly into DXGI, this would mean writing something very Windows specific. The documentation for DXGI is also incredibly sparse. How to do a mode switch using DXGI directly rather than the D3D11/12 devices is not remotely clear to me, for example.

GZDoom simply does not have the developer resources available to do this.

**Comment by HybridEidolon** [comment]
ZVulkan definitely uses `VK_EXT_full_screen_exclusive`, which I'm sure will fix the issue provided the driver supports the extension. For what it's worth though, I don't believe Windows 10 has "exclusive fullscreen" in the traditional sense at all. The compositor does some tricks ("fullscreen optimizations") to get exclusive fullscreen-like performance while still treating it like a normal window, which includes the flip swapchain effect that enables VRR to work, and applications will see that as "exclusive" even if it's not.

Nvidia's GL is implemented over Vulkan but I am convinced that the KHR windowing and swapchain extensions are not using the same codepath as their DXGI implementation. I can't think of any reason otherwise for the odd swap behavior. Recently [nvidia added support for configuring the swapchain creation for OpenGL and Vulkan KHR display](https://i.imgur.com/o8A5roZ.png) with some interesting notes about compatibility that may explain why the behavior is not so clear-cut.

![](https://i.imgur.com/o8A5roZ.png)

I've been in the process of rewriting SRB2's renderer and noticed that fullscreen VRR works fine on Nvidia GL now without any code changes, possibly thanks to the aformentioned new driver feature. I'm on 526.98, for reference.

Maybe there's a missing piece of the puzzle here for getting proper "immersive fullscreen" and windowed flip swap behavior on Windows from Nvidia without going cross-API. Or maybe it's best to just leave it to the driver to handle these cases now?

> How to do a mode switch using DXGI directly rather than the D3D11/12 devices is not remotely clear to me, for example.

AFAIK, [`IDXGISwapChain::ResizeTarget`](https://learn.microsoft.com/en-us/windows/win32/api/dxgi/nf-dxgi-idxgiswapchain-resizetarget) with [`DXGI_SWAP_CHAIN_FLAG_ALLOW_MODE_SWITCH`](https://learn.microsoft.com/en-us/windows/win32/api/dxgi/ne-dxgi-dxgi_swap_chain_flag) set on the swapchain allows changing modes when resizing a swapchain that's in fullscreen mode.

**Comment by dpjudas** [comment]
OK, calling ResizeTarget seems simple enough, but now my problem is how to create the swap chain object in the first place. The only obvious candidate I can spot is IDXGIFactory2::CreateSwapChainForHwnd, but its first argument is a pointer to a D3D11/D3D12 device. The documentation explicitly states that it cannot be null.

I'm still not sure how to create such a swap chain without creating a D3D11/12 device. Maybe that's what the driver does behind the scenes for the DXGI Swapchain method? I honestly don't know.

In any case, I think it is better to try track down what issue might be preventing VRR from being active with the vulkan swap chain rather than try bridge into DXGI directly. Vulkan is new enough that they did know about VRR when they designed it.

**Comment by HybridEidolon** [comment]
The device is needed to be able to create device allocations and submit copy and present operations to the command buffer, just like Vulkan, yes. But the inability of KHR swapchains to participate in flip model presentation on Windows is probably a design limitation in the extension that drivers (ala the Nvidia solution) have to work around or simply not support.

I agree it's non-ideal that the programmer needs to know the specifics of both APIs to get optimal swapchain user experience with Vulkan on Windows, but at least the option's there if someone comes around to implement it.

**Comment by coelckers** [comment]
vkDoom already has it so it'll be done when that code gets backported.
