### ISSUE TITLE
[BUG] Plasma Rifle Flash shows when you stop firing.

### ISSUE THREAD

**Issue by yum13241** [ZDoom/gzdoom#2037]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

EndeavorOS

### Relevant hardware info

None relevant.

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

![image](https://user-images.githubusercontent.com/91150826/228597006-1546d765-9d54-4508-9698-a5dc6da55621.png)

You fixed the SSG flash timing bug, why not fix this?

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Fire the Plasma Rifle.
2. Stop firing.
3. Immediately press the PAUSE key.

### Your configuration

```ini
None relevant.
```

### Provide a Log

None relevant.

**Comment by coelckers** [comment]
It's a known definition error from Doom.exe. We decided not to fix it for compatibility reasons.

**Comment by mc776** [comment]
Can I ask what the difference is between this situation and the SSG?

Looking at the definition in WhackED it seems no more or less problematic to fix - just reduce this one frame that doesn't call anything but Light1 by 1 tic:
![image](https://user-images.githubusercontent.com/24984517/228614169-659a2e1f-e1dd-4833-a0b2-c24232d30863.png)

**Comment by yum13241** [comment]
> It's a known definition error from Doom.exe. We decided not to fix it for compatibility reasons.

Then why did the SSG get fixed?

Maybe revert the fix if a DeHackEd patch gets applied.

**Comment by mc776** [comment]
I've just tried this in Chocolate Doom and GZDoom:
```
Frame 79
Duration = 3

Frame 80
Duration = 3
```

Pros: Looks a lot more convincing.

Cons: That flashing looks like it can give someone a seizure. (It's a lot less awful in GZDoom with my setup but my setup has GL and Bright sector lighting and dynamic lights so A_Light effects are barely noticeable in the first place.)

That all said, either with or without this adjustment I can't see any overlap between PLSF* and PLSGB0, and any improvement I see is just a matter of making it look like it's moving instead of being stuck in the same flash frame for unduly long periods of time...

**Comment by yum13241** [comment]
> We decided not to fix it for compatibility reasons.

What would it break compatibility with?

> Cons: That flashing looks like it can give someone a seizure.

Doom powerups can cause seizures but they were never changed.
