### ISSUE TITLE
[Feature] Flick Stick controls

### ISSUE THREAD

**Issue by puddydoo** [ZDoom/gzdoom#2038]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

Flick Stick is a good alternative gamepad control scheme, especially with Doom not needing vertical aim.

### Describe alternatives you've considered

Programs like JoyShockMapper and Steam Input can be used to play GZDoom with flick stick, but in order for it to work properly the user must first calibrate it to the camera sensitivity. And the correct pixel value will also change depending on the scaling of GZDoom. For me, i use steam deck, with normal scaling and default sensitivity, and got it to work at 2048 pixels. An in-engine implementation would be more convenient by not requiring the user to painstakingly figure out the exact number of pixels to set it to for their personal setup.

### Add any other context or screenshots about the feature request here.

https://en.wikipedia.org/wiki/Flick_Stick

**Comment by CandiceJoy** [comment]
I stand to be corrected, but I doubt any GZDoom developers have a flick stick, unless an Xbox/Playstation/Nintendo controller with built-in gyroscopic controls counts?

**Comment by puddydoo** [comment]
Flick stick can work with any controller, it simply changes the in-game operation of the stick you would normally use for aiming. In the context of doom where vertical aim isn't important, a gyroscope implementation isn't strictly necessary for flick stick, though it's still a good complement to it, so I put gyro as a separate feature request.

**Comment by G-F-D** [comment]
My understanding is that GZDoom presently has no sense of angle when it comes to analogue inputs — it just directly assigns axes to movement or turning, which works for all 5 of the current analogue controls (movement along 3 axes, pitch, yaw). Supporting this specific feature would necessitate either:

1. Overhauling controller input handling in general, to better support non‐direct control methods like flick stick and gyroscopic controls (requires a _lot_ more work and testing for relatively little benefit to the userbase, considering most users still play Doom‐engine games with KB+M setups); or
2. Carving out some exceptions in the input handling for this case.

Much as I’d also like to see more advanced input features be natively well‐supported, the second option naturally sounds more appealing from a development perspective. It would require adding 2 new axis types to the current menu (“Flick Stick X” and “Flick Stick Y” or similar) and then using both of those axis types as a 2D vector behind the scenes. The other axis options don’t need to change:

* “Invert” would still be used normally on all axes,
* “Overall sensitivity” would control how sensitive turning is after choosing a facing angle (i.e. for one full circle rotation on the stick, the player is turned 360° × sensitivity)
* “Dead zone” would indicate the distance threshold from centre for registering new “flicks”.

The latter 2 options can’t be independent for each axis, so I would just use the values configured on the first “Flick Stick X” axis. (Keeping the settings in sync with all the flick stick axes when changing one from the menu would be a bonus for helping users understand how this works, but is not strictly necessary.)

Since syncing the sensitivity and dead zone settings for flick sticks across controllers doesn’t make any sense, but trying to use different settings from different controllers for the same flick stick state management behind the scenes doesn’t make sense either, it would probably be best to keep track of the flick stick state for each controller separately. (This limits each controller to having 1 functional flick stick, but this also seems reasonable.)

**Comment by AL2009man** [comment]
> My understanding is that GZDoom presently has no sense of angle when it comes to analogue inputs — it just directly assigns axes to movement or turning, which works for all 5 of the current analogue controls (movement along 3 axes, pitch, yaw). Supporting this specific feature would necessitate either:
> 
> 1. Overhauling controller input handling in general, to better support non‐direct control methods like flick stick and gyroscopic controls (requires a _lot_ more work and testing for relatively little benefit to the userbase, considering most users still play Doom‐engine games with KB+M setups); or
> 2. Carving out some exceptions in the input handling for this case.
> 
> Much as I’d also like to see more advanced input features be natively well‐supported, the second option naturally sounds more appealing from a development perspective. It would require adding 2 new axis types to the current menu (“Flick Stick X” and “Flick Stick Y” or similar) and then using both of those axis types as a 2D vector behind the scenes. The other axis options don’t need to change:
> 
> * “Invert” would still be used normally on all axes,
> * “Overall sensitivity” would control how sensitive turning is after choosing a facing angle (i.e. for one full circle rotation on the stick, the player is turned 360° × sensitivity)
> * “Dead zone” would indicate the distance threshold from centre for registering new “flicks”.
> 
> The latter 2 options can’t be independent for each axis, so I would just use the values configured on the first “Flick Stick X” axis. (Keeping the settings in sync with all the flick stick axes when changing one from the menu would be a bonus for helping users understand how this works, but is not strictly necessary.)
> 
> Since syncing the sensitivity and dead zone settings for flick sticks across controllers doesn’t make any sense, but trying to use different settings from different controllers for the same flick stick state management behind the scenes doesn’t make sense either, it would probably be best to keep track of the flick stick state for each controller separately. (This limits each controller to having 1 functional flick stick, but this also seems reasonable.)


Theoretically: implementing Flick Stik can be done without requiring a controller overhaul, which means we'll need to take a look at how Mouse Camera (`PostMouseMove`) works, repurpose it and then add it to the main menu. 

 I decided to ask the funni Copilot thing to provide for me a quick example just for fun..don't use that code, [reference GyroWiki instead](http://gyrowiki.jibbsmart.com/blog:good-gyro-controls-part-2:the-flick-stick). 

```
#include <cmath>
#include "d_event.h"

// Helper: Converts angle in radians to mouse delta (tune this for your sensitivity)
float FlickAngleToMouseDelta(float angle_diff_radians)
{
    // Example: map the angle (radians) to an equivalent mouse delta (arbitrary scale)
    // You may need to adjust the multiplier for your engine's sensitivity
    const float mouse_sensitivity = 40.0f; // Tune this constant as needed
    return angle_diff_radians * mouse_sensitivity;
}

// Flick Stick state (persist across calls)
struct FlickStickState {
    float last_angle = 0.0f;
    bool initialized = false;
};

void ProcessFlickStick(float stick_x, float stick_y, FlickStickState &state)
{
    // Ignore small values (deadzone)
    const float deadzone = 0.3f;
    float mag = std::sqrt(stick_x * stick_x + stick_y * stick_y);
    if (mag < deadzone) {
        state.initialized = false;
        return;
    }

    // Calculate angle in radians (0 is right, pi/2 is up, etc.)
    float angle = std::atan2(-stick_x, -stick_y); // Adjust sign as needed for your engine

    if (!state.initialized) {
        state.last_angle = angle;
        state.initialized = true;
        return;
    }

    // Compute angular difference (wraps around)
    float delta = angle - state.last_angle;
    while (delta > M_PI) delta -= 2 * M_PI;
    while (delta < -M_PI) delta += 2 * M_PI;

    // Convert angle delta to mouse delta and post event
    float mouse_dx = FlickAngleToMouseDelta(delta);
    PostMouseMove(static_cast<int>(mouse_dx), 0);

    state.last_angle = angle;
}
```

You can also reference how other sourceports (like Yamagi Quake 2, Ironwail and woof) handle it, but for ease of case: [I'll link one from ironwail](https://github.com/andrei-drexler/ironwail/blob/32a3879d93ab65c9c505e3fb91a386c64ebf271e/Quake/in_sdl.c#L1084) and [woof](https://github.com/fabiangreffrath/woof/blob/master/src/i_flickstick.c)

The real problem is that Flick Stick is heavily reliant on Gyro Camera controls to make it work, we'll need to deal with https://github.com/ZDoom/gzdoom/issues/2039 ...but that also means replacing the existing GZDoom Input system with SDL...**which GZDoom already uses on the Linux side**. (refer to https://github.com/ZDoom/gzdoom/issues/3093)

....but we might not need a Gyro Camera within the context for Classic Doom. :P
