### ISSUE TITLE
[Feature] Gyroscope controls

### ISSUE THREAD

**Issue by puddydoo** [ZDoom/gzdoom#2039]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Is your feature request related to a problem? Please describe.

I think there should be support for gyroscope aiming, such as with certain PlayStation/Nintendo/Steam controllers.

### Describe alternatives you've considered

Programs like JoyShockMapper and Steam Input can be used to play GZDoom with gyroscope controls.

### Add any other context or screenshots about the feature request here.

Gyro support is in the official Unity ports of Doom 1/2.

**Comment by coelckers** [comment]
If someone contributes such a feature, we will take it, but none of the devs uses such hardware.

**Comment by AL2009man** [comment]
> If someone contributes such a feature, we will take it, but none of the devs use such hardware.

due to the current GZDoom Input system limitation, the contributors can't really contribute without https://github.com/ZDoom/gzdoom/issues/3093, and that's a big undertaking, even for me. But, I am more willing to contribute portions of it as I've done so with Perfect Dark's PC Decompilation project (still WIP tho), if the Controller overhaul also includes SDL Gamepad API.

even moreso in the advent of [GyroHelpers library](https://github.com/NaokoAF/GyroHelpers) that makes Gyro Aiming easier to implement, but again: we'd need to implement SDL Gamepad API *first*.
