### ISSUE TITLE
Can't set infighting CVAR to -1 through command line

### ISSUE THREAD

**Issue by Q3BFG10K** [ZDoom/gzdoom#2043]
GZDoom 4.10, Win10-64.

https://zdoom.org/wiki/CVARs:Configuration

This works fine from the shortcut: 
`+set infighting 1`

These don't work:
```
+set infighting -1
+set infighting "-1"
```

It refuses to set it to **-1** and instead defaults to 0.

**Autoexec.cfg**
```
set infighting -1
```

Works fine. Am I doing something wrong or is this a bug?

**Comment by prof-hastig** [comment]
This is an inherent limitation of the command line. It considers '-' a command line switch which makes it impossible to parse the -1 in this case as a parameter. To get it to work you have to enclose the entire command in quotes, i.e. "+set infighting -1"
The underlying cause here is the same that requires to put quotation marks around file names with spaces.

**Comment by coelckers** [comment]
Ok then, filed under "can't fix"

**Comment by Q3BFG10K** [comment]
Quotes did the did the trick, thanks all.
