### ISSUE TITLE
[BUG] Ubuntu package does not work on 23.04

### ISSUE THREAD

**Issue by daemonspudguy** [ZDoom/gzdoom#2059]
### GZDoom version

GZDoom 4.10.0

### Which game are you running with GZDoom?

Doom

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Ubuntu 23.04

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When installing the package for Ubuntu, it doesn't work because a dependency, libflac8, does not exist on Ubuntu 23.04 and has been replaced with libflac12

### Steps to reproduce the behaviour.

1. Run Ubuntu 23.04
2. Attempt to install GZDoom

**Comment by madame-rachelle** [comment]
@Blzut3 Do you have any idea how best to handle this?

**Comment by Blzut3** [comment]
Yes, I was going to make some adjustments in the next release (whatever that might be).  But in the mean time there are three options:

1. Install the DRD Team APT repo. As always with these transitions, it provides an extra package which will be installed automatically to satisfy the dependency.  (Follow directions on https://debian.drdteam.org)
2. Install that extra package manually: https://debian.drdteam.org/pool/multiverse/f/flac/drdteam-libflac8_1.3.4_amd64.deb
3. If for some reason you don't trust my build of the library, you can also just manually download and install the package from Ubuntu 22.10: https://packages.ubuntu.com/kinetic/amd64/libflac8/download  It will work fine on 23.04.

An advantage to doing 1 is the package will be automatically uninstalled when no longer needed with no further actions necessary.  Although the same can be achieved with 2 and 3 by manually marking the package as automatically installed (exercise for the reader since I recommend just doing option 1).

Note that this only applies to the x86 build.  The repo has started to provide ARM64 builds which by virtue of being new, have been built to account for the ABI transition.

Aside: I was a little surprised Ubuntu removed libflac8 immediately since they, unlike Debian, usually provide an old version to be ABI compatible with the LTS for stuff in the main repo, which is usually enough time to transition.

**Comment by daemonspudguy** [comment]
I didn't know that DRD Team had an APRT repo. TIL.
