### ISSUE TITLE
[BUG] Screen tearing in fullscreen if game is started with vsync on and Vulkan

### ISSUE THREAD

**Issue by Macil** [ZDoom/gzdoom#2066]
### GZDoom version

4.10.0

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10 Home

### Relevant hardware info

Intel i7-6900K, Nvidia 2080 Ti

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

I've noticed screen tearing happening while vsync is on. It's my understanding that vsync should fully prevent screen tearing.

This only happens for me when in fullscreen, and if the game was started in vulkan mode with vsync turned on.
If I turn vsync off and then back on, then vsync will work correctly from that point on while GZDoom is running and prevent screen tearing. So it seems like when I start the game with the vsync setting turned on, vsync is somehow in a broken state.

I've noticed a minor quirk unique to this broken vsync state: if I've started the game with vsync on, then the first time I turn vsync off, the screen turns fully black for a moment as the setting changes. After I've exited the broken vsync state, that never happens again: toggling vsync works smoothly immediately with no screen flicker hiccup.
This makes me suspicious that there might be something that GZDoom is not doing correctly for vsync on startup, but is being done correctly on toggling.

---

Screen tearing happens very commonly for me if I have "vid_maxfps 60" set (I can see it in map01 just looking around quickly), but it seems like it can still happen whenever performance takes a drop (like in MyHouse which uses a lot of portals and causes my fps to go below 60 at times).

The issue doesn't seem present when I'm not in fullscreen, though I'm not sure if that's just because performance quirks or because there's some other factors relevant to screen tearing unique to non-fullscreen windows.
Screen tearing still happens if I exit fullscreen and then re-enter it.

This bug still happens with the software renderer if I'm using Vulkan.

I do not see this behavior when using OpenGL mode.
I do not see this behavior in other open source Vulkan games like vkQuake.

**Comment by coelckers** [comment]
How does vkDoom fare on your system? It got a more modern version of the Vulkan renderer.

**Comment by Macil** [comment]
I get the same issue and same exact behavior in vkDoom 0.9. (I've also retested in the latest Gzdoom, 4.11.3, and it's still the same.)

I've tested a number of things to see if the issue might be dependent on them, and the issue has been unaffected:
- I recently replaced my CPU and motherboard so I have an AMD 4950x3d, and I have a fresh Windows 11 install with the latest nvidia drivers and all. I still have the same behavior now.
- I have two 60hz non-gsync monitors. I've tried with both connected and with each one by itself.
- I've tried a few different resolutions and scaling settings to see if it the issue was dependent on it but it seems unrelated.

My testing procedure is to make sure Gzdoom is set to vulkan, 60 max fps, vsync on (restarting after changing if I've changed it within the session), start doom 2 at map01, and rapidly move the mouse left or right. 3/4 the time screen tearing is immediately apparent. The rest of the time, tearing becomes obvious after a few minutes. I've found that if I restart the map with "map map01" in the console, it re-rolls the chance of tearing becoming obvious, so I can quickly figure out if I'm vulnerable to tearing by doing that if I don't immediately spot the tearing.

**Comment by Macil** [comment]
I've figured out two things:

1. When gzdoom is in the problem state (when I've started with vsync on and have not toggled it within the current game), screen tearing is constant if I do "vid_maxfps 60" or any smaller value, but only happens for about a frame every few seconds on MAP01 if I do "vid_maxfps 61". I think while gzdoom is in the problem state, screen tearing only happens whenever my framerate dips to 60 or below. (When I've exited the problem state by toggling vsync off and then on, no screen tearing happens even my framerate dips below 60.)

2. The recent unreleased commits in the repo, 58acf528bf3b18c28377a6961cc1375049ca2a2d (it doesn't build for me but I assume it's responsible for the change) or 9ff1193dabacbee5d6d8b310c932575f31ccd049 have made this problem worse: turning vsync off and on no longer fixes the issue. No matter what now, while vsync is on, I'm in the problem state where I get screen tearing if my framerate dips to 60 or below. (I also noticed a small behavior change around the vsync menu option: the screen always blanks for a moment when I change the option, as opposed to before when it would only blank for a moment the first time I turn vsync off.)

**Comment by Macil** [comment]
I believe I've figured out that there are two separate underlying issues here. Conclusions up front:
1. When vsync is on, Gzdoom uses VK_PRESENT_MODE_FIFO_RELAXED_KHR (instead of VK_PRESENT_MODE_FIFO_KHR) which specifically allows screen tearing if the application falls below the refresh rate. (https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/VkPresentModeKHR.html) Maybe Gzdoom should add a cvar to opt out of this.
2. When vsync is on **and** vid_maxfps is set to equal or below your refresh rate, then you're almost guaranteed continuous screen tearing because of some interaction of the settings. Any vsync user that attempts to "optimize" their setup like me by setting their max framerate right to their display framerate is setting themselves up for this issue.

---

I looked for references to vsync in the code and noticed I never had any screen tearing once I commented out these two lines:

https://github.com/ZDoom/gzdoom/blob/682dd1b22dc9af32496119615eed09f0ee9a3518/libraries/ZVulkan/src/vulkanswapchain.cpp#L115-L116

This makes sense because reading about VK_PRESENT_MODE_FIFO_RELAXED_KHR, it seems like it specifically allows screen tearing when the application framerate drops. This explains my memories (before I changed my vid_maxfps setting) of only seeing an occasional screen tear when the framerate dipped.

However, this doesn't explain why I started getting continuous screen tearing after setting vid_maxfps to 60 in an attempt to optimize my setup and avoid screen tearing.

![PXL_20240328_022256461](https://github.com/ZDoom/gzdoom/assets/577345/3900b9a5-0cbe-429c-a773-48d094303ed5)

When I set vid_maxfps to 60, then I usually have a continuous screen tear like this. I believe it's showing a newer frame below the tear. The interesting thing is that the tear usually stays at a specific height on the screen for a while. This height randomly changes whenever I have any kind of frame drop, including from opening the console or loading a new map.

If I set vid_maxfps to 59, then the continuous screen tear moves down my screen and wraps around to the top about once a second. If I set vid_maxfps to 58, then it moves down twice as fast, 57 maybe three times as fast. At much lower values it just looks like it's at random spots because it jumps so much per frame and wraps often.

I think at vid_maxfps 59 it's moving 1/60th (ie. (60-59)/60) (or 1/59th dunno) of my screen down every frame, etc.

If Gzdoom implements vid_maxfps by adding a delay at the start of generating a frame if it's been less than 1/vid_maxfps seconds since the last frame was generated, then I think this fully explains the issue. If vid_maxfps and your screen refresh rate are both 60, and then something hitches the game for a moment, you can have a situation where the last frame was generated 5ms ago when the display asks for a frame, the framerate-limiting code waits 16 - 5 = 11ms before generating the next frame, which gets delivered late while the display is rendering the bottom of the screen, and then 5ms later the display asks for another frame in the same situation leading to a tear in the same part of the screen again. And if vid_maxfps is set to below your screen refresh rate, then the framerate-limiting code will always be delaying during each frame and causing a tear.

Maybe there's a way to do framerate limiting in a more vsync friendly way that gets around this, but otherwise it seems to me like vid_maxfps should just be ignored entirely when vsync is on if it is the case that it's broken when it's below your screen refresh rate and a no-op when it's above your screen refresh rate.

**Comment by madame-rachelle** [comment]
I would suggest forwarding your suggestion along to [VkDoom](https://github.com/dpJudas/VkDoom/) because GZDoom's Vulkan renderer is effectively deprecated, but not only that the change you are requesting is in the ZVulkan library - the master of which is not maintained locally on GZDoom. Making GZDoom-specific changes to the library is effectively setting ourselves up for failure because when the upstream changes come down they either get wiped out or cause maintenance conflicts/eventual nightmares.

**Comment by dpjudas** [comment]
GZDoom and VKDoom both uses the same swap chain code here (GZDoom was updated to the latest version a few months back), so they behave identical in this manner.

About the complaint itself, IMHO this is really about gamers (no offense meant) using settings that they read about on the internet as "best practice" without realizing why it was optimal for one specific game and now attempts to apply it across the board. Sometimes even only relevant for a specific version of Windows.

GZDoom uses the relaxed mode because if you happens to be playing something that is right at the limit of the refresh rate then the game ultimately has no choice but to do one of two things:

1) If it is not using relaxed FIFO, then it misses the present deadline and needs to wait a full vsync period to display it. What is even worse is that when it is finally shown, the image is now additionally out of date visually, creating potentially a very nasty stutter effect. Lets say we have a 60 hz monitor and the time it takes to create some scenes are (A) 18 ms, (B) 14 ms, (C) 18 ms, (D) 18 ms, (E) 14 ms, (F) 14 ms, (G) 18 ms. In this situation the user will see the frames visually on the display as: ABBCCDEFFG. So some frames stay put on the screen twice as long as others.

It gets even worse though, since each frame isn't just a frame. The frame-create-to-photon time gets delayed by 16 ms each time it misses the deadline. When you finally see a delayed frame, such as frame C, it is now 16 ms older than what was needed to ensure a consistent time flow from frame to frame. The stutter effect goes through the roof.

2) The game can use relaxed FIFO and minimize the damage to a visual tear. Pacing remains much more stable and the overall experience doesn't really suffer as much as from the above described situation. The tear never really moves consistently down the screen like you describe as that generally only happens with a fixed synthetic frame time like maxfps produces.

This topic is sufficiently advanced in general that I don't think it is a good idea to give the users an option of selecting the present method. That will just lead to a bunch of people feeling with incorrect settings. I much more like your suggestion of simply ignoring maxfps entirely when vsync is enabled. That will also let the average gamer out there set it to 59 fps for a 60 hz monitor and feel they "optimized" their input latency without ever really doing anything and be none the wiser. :)
