### ISSUE TITLE
[BUG] 4.11 crashing when run in OpenGL mode with certain settings

### ISSUE THREAD

**Issue by GrayFace** [ZDoom/gzdoom#2139]
### GZDoom version

GZDoom-x64-g4.11pre-279-g22271d146

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 7

### Please describe your specific OS version

Windows 7 x64

### Relevant hardware info

AMD Ryzen 5 2600, Radeon RX 570

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When run with these settings: [gzdoom_portable.zip](https://github.com/ZDoom/gzdoom/files/12463633/gzdoom_portable.zip)
new version of GZDoom crashes: [CrashReport.zip](https://github.com/ZDoom/gzdoom/files/12463634/CrashReport.zip)
The crash doesn't happen in Vulkan mode.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Run the game. E.g. with doom2.wad or freedoom.wad
2. Start the first level on any difficulty
3. Crash occurs, the report is attached above

### Your configuration

```ini
See above
```

### Provide a Log

See above

**Comment by coelckers** [comment]
Doesn't crash for me with that INI.

**Comment by madame-rachelle** [comment]
You are using an AMD RX 570; I would suggest against using OpenGL with this card, since Vulkan is far more stable and runs better.

Since the debug symbols are no longer published with devbuilds, it makes debugging things like this much more difficult. If you can get a reliable crash in a release build (4.11) I can take another look at this, but otherwise, this looks to be a dead end. I recommend to use Vulkan.

**Comment by GrayFace** [comment]
Checked in the release build and it didn't crash.
At the time of filing the bug report I was already using Vulkan, it improves performance drastically. I just happened to encounter this crash with OpenGL.
