### ISSUE TITLE
[Feature] Issues with Doom's obituaries

### ISSUE THREAD

**Issue by mc776** [ZDoom/gzdoom#2187]
These have bothered me for years but since we've got #2186 I might as well post about them.

I hesitate to label this as "bug" the same way as that issue though, since they're not quite the same glaring inconsistencies for a game with much fewer eyes on it than Doom.

> %o was slashed by an imp.

There is no reasonable way that the movement depicted in TROOE-G - to say nothing of the sound effect when the attack lands - can be considered "slashing". Was this originally left over from copypasting the Heretic sabreclaw?

> %o was smitten by a cacodemon.

I think the intention here had been to refer to smiting by lightning, but I've pretty much never seen the word "smitten" outside of the sense of "she's so smitten with this boy band she's got posters all over her room", etc..

### Describe the solution you'd like

Perhaps "scratched" and "zapped" respectively?

### Describe alternatives you've considered

"Ionized" could be fun for the caco too.

**Comment by prof-hastig** [comment]
Read my comment in the equivalent Hexen report. Very much the same applies here.

**Comment by mc776** [comment]
You were free to just... not comment, lol.

**Comment by madame-rachelle** [comment]
So someone posts twice that they disagree with you, and that's too much for you? Sorry but this whole issue was a weak argument to begin with, and seeing the way you disagreed with professor hastig that weakens it even more. I think there's no merit to this. Furthermore, if you wish to propose changes to the language strings, the source is not the proper place to do it, since GZDoom imports its strings from a Google Docs page. You can find more information about this setup here: https://forum.zdoom.org/viewtopic.php?t=63737

**Comment by madame-rachelle** [comment]
I do think these proposals actually do merit a more open discussion, but it should happen in the thread where it is more populated and people are paying more attention. Making things sterile and boring with the obituaries is definitely a direction that I do not wish to go. However, there may be things not argued yet that I haven't considered on this issue and I definitely would want to see them. So let's take everything to the ZDoom thread - https://forum.zdoom.org/viewtopic.php?t=63737 - and discuss it there.
