### ISSUE TITLE
Revert sector light mode changes?

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2194]
Personally I feel like GZDoom is lacking with the ability to set the light mode to "bright" and what not. The whole thing was meant to be overridable for the user's preference.

**Comment by madame-rachelle** [comment]
Does `gl_maplightmode` not suit your needs?

**Comment by MajorCooke** [comment]
If that's the case, there should be a menu option to go through it, shouldn't there? Because all I have right now is "Classic (Faster)",  "Software" and "Vanilla".

I'd just like to be able to set the styles of "Bright", "Doom", etc somewhere instead of just in the console.

**Comment by coelckers** [comment]
This was demoted to a map option for good reasons because setting the wrong light mode really can screw up how a map looks.
In summary the feature as previously implemented drew lots and lots of complaints but very little praise, primarily from mappers who were concerned that people would get a bad impression for the lighting in their maps.

If you need 'bright' on a regular basis you need to recalibrate your monitor anyway.

**Comment by GrayFace** [comment]
Just write "(not recommended)" in mode descriptions. This feature is actually essential. No gamma correction or brightness adjustment can fix pitch black places without making the bright places overly bright. While I did jump through the hoops of creating an autoexec.cfg with "gl_maplightmode 0", this shouldn't be required.

**Comment by MajorCooke** [comment]
[I restored it as an addon.](https://forum.zdoom.org/viewtopic.php?p=1245996#p1245996)

**Comment by Dacatzgoescodin5267** [comment]
I agree with these people, since it sucks and barely see shit, just bring back the modes

**Comment by MajorCooke** [comment]
Yep. Well I have an addon posted above so you can have it back.
