### ISSUE TITLE
[BUG] file/product version missing in CI builds

### ISSUE THREAD

**Issue by liPillON** [ZDoom/gzdoom#2209]
### GZDoom version

latest CI build

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

not relevant

### Relevant hardware info

not relevant

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

The current CI artifacts for Windows (VS 2019 release, VS 2022 release, VS 2022 debug) are generated without updating the executable's product version information.

While we're here, may I suggest renaming the CI worflows, detailing what kind of artifacts they generate? (Windows vs AppImage)?

Comparing 'gzdoom.exe' file properties in Beyond Compare:

![Screenshot 2023-10-11 142506](https://github.com/ZDoom/gzdoom/assets/48625273/82a3c528-170b-40ce-8768-d7924fcb6e24)

### Steps to reproduce the behaviour.

1. download the latest CI artifacts for Windows from Github
2. check 'gzdoom.exe' file properties 
3. compare them with the 4.11 release build

### Your configuration

```ini
not applicable
```

### Provide a Log

not applicable

**Comment by alexey-lysiuk** [comment]
The version info is missing because checkout action does a shallow clone to speed up the process.
Produced artifacts are not supposed to be used as replacement of development builds. The sole reason of their existence is to be able to check them quickly if something goes wrong on CI runners side.
Also, nobody will rename workflows just because someone doesn't like their names.
