### ISSUE TITLE
[Question/Docs] Request for Clarification on Compiling Portable Variant on Linux

### ISSUE THREAD

**Issue by AvinashReddy3108** [ZDoom/gzdoom#2286]
Hello GZDoom Developers,

I hope this message finds you well. I am currently in the process of compiling GZDoom on Linux for personal reasons, following the instructions provided on the [GZDoom Wiki](https://zdoom.org/wiki/Compile_GZDoom_on_Linux).

While reviewing the [build options](https://zdoom.org/wiki/Compile_GZDoom_on_Linux#Build_options) and [compile commands](https://zdoom.org/wiki/Compile_GZDoom_on_Linux#Compiling), I noticed that the documentation lacks information on building a portable variant of GZDoom, similar to the ones available in the [Releases](https://github.com/ZDoom/gzdoom/releases/latest).

I kindly request your assistance in providing clear instructions on how to compile a portable variant of GZDoom on Linux. I am particularly interested in understanding the necessary build options and compile commands to achieve a result similar to the portable versions available in the official releases.

Thank you for your time and support. Your guidance will be greatly appreciated.

Best regards

**Comment by madame-rachelle** [comment]
For the time being, even though this guide was written for Windows it works well enough for Linux. Make sure to install cmake-gui from your package manager, as well as libopenal-soft, as well as gcc, g++, or clang, and whatever package provides glibc. Then clone vcpkg to a working folder and point cmake's toolchain exactly as described in this linked thread.
https://forum.zdoom.org/viewtopic.php?t=78107

The libraries are gathered with a shell script, similar to this one: (You will have to edit this to match your build environment folder structure)
```bash
#!/bin/bash
export SOURCE=~/Projects/gzdoom-g4.11.1/build
export TARGET=~/Projects/gzdoom-g4.11.1-linux-portable
cp $SOURCE/gzdoom $TARGET
cp $SOURCE/*.pk3 $TARGET
ldd $TARGET/gzdoom | awk 'NF == 4 { system("cp " $3 " $TARGET") }'
cp /lib/x86_64-linux-gnu/libopenal.so.1 $TARGET
cp -R ../gzdoom-g4.11.1/build/soundfonts/ $TARGET/soundfonts
cp -R ../gzdoom-g4.11.1/build/fm_banks/ $TARGET/fm_banks```

GZDoom must be `strip`ped before distribution. If you compiled any libraries (like ZMusic) they should be `strip`ped also.

If you want to push .tar.xz packages, I suggest using "fakeroot" before tar'ing the archives, but that is optional.

**Comment by madame-rachelle** [comment]
Correct on both counts. GZDoom includes an instruction in its cmakelists that sets its rpath to ${ORIGIN} to allow it to use some of the libraries in its own folder. Raze includes a similar setup but you'd use zmusiclite.so.1 instead of zmusic.so.1 (but the ldd might catch that it anyway).

Indeed, ${ORIGIN} does not seem to work for all libraries, but it works for most. `ldd` will tell you if it's not using any libraries inside the folder after they are copied over. I am not really sure what to do in these situations, this is going into territory where the only solution might require those virtual filesystem layers, like flatpaks/snaps/appimages.
