### ISSUE TITLE
[BUG] Very fatal error when exiting the game with Holiday Hits loaded

### ISSUE THREAD

**Issue by proydoha** [ZDoom/gzdoom#2298]
### GZDoom version

GZDoom 4.11.3

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Please describe your specific OS version

Windows 11 Home

### Relevant hardware info

i7-7700, GeForce GTX1070

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Game crashes with a very fatal error after exiting when Holiday Hits are loaded.

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Load the game with Holiday Hits [https://forum.zdoom.org/viewtopic.php?t=78562](https://forum.zdoom.org/viewtopic.php?t=78562)
2. Exit the game
3. Very fatal error

### Provide a Log

[CrashReport.zip](https://github.com/ZDoom/gzdoom/files/13665239/CrashReport.zip)

**Comment by Player701** [comment]
It does crash for me in 4.11.3, but I'm no longer able to trigger the crash in g4.12pre-214-g273f7c55b. I guess the underlying cause might have already been fixed since the 4.11.3 release.

@proydoha Just in case, please also try the latest [devbuild](https://devbuilds.drdteam.org/gzdoom/) and see if it still crashes for you.

**Comment by proydoha** [comment]
@Player701 Does not crash in g4.12pre-214-g273f7c55b 👍
