### ISSUE TITLE
"The solution you provided was incorrect" forum error

### ISSUE THREAD

**Issue by Candlemass** [ZDoom/gzdoom#2401]
### GZDoom version

N/A

### Which game are you running with GZDoom?

None

### What Operating System are you using?

None

### Please describe your specific OS version

Android

### Relevant hardware info

N/A

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Can't nmake any posts on the forum. Keep receiving error "the solution you provided was incorrect". This is the only forum this occurs on. Why?

### Steps to reproduce the behaviour.

Login to forum account.
Try to reply to a thread or create a new thread.

**Comment by Candlemass** [comment]
Hello?

The forum is broken...

**Comment by RicardoLuis0** [comment]
this github isn't for forum issues, you should try to contact a moderator on the discord instead (via the #contact-moderators channel)

**Comment by Candlemass** [comment]
> github issues aren't for forum problems, you should try to contact a moderator on the discord instead (via the #contact-moderators channel)

@RicardoLuis0

If the forum wasn't broken then I could actually post to bring the problem to the attention of someone there.

I don't use discord.

Please provide an email address for someone that I can get a hold of.

**Comment by madame-rachelle** [comment]
They don't give public email addresses because it'd be impossible to properly monitor with how much of a spam magnet it'd be.

If you need to communicate with the developers this Github is as good a place as any to do it. If you want to create a forum account then you need to get in touch with the moderators, and Ricardo already gave you the information to get in touch with them. Some basic troubleshooting to keep in mind is that it uses Recaptcha which is a Google service, make sure you aren't filtering that in your browser. It also checks your IP address against blackholes, make sure you aren't using a public VPN that gets frequently abused for the purpose of bypassing stuff. If you absolutely must use a VPN I would suggest switching to a privately managed one that the general public cannot use as easily. Beyond that you really need to get in touch with the moderators and the only places to do that is the forum or Discord.

It might be worth a try to post here: https://forum.zdoom.org/viewforum.php?f=58 - other than this, we cannot help you further. I am sorry.
