### ISSUE TITLE
[BUG] GetEntryReader causes fopen to fail with EMFILE when called from a non-main thread

### ISSUE THREAD

**Issue by RicardoLuis0** [ZDoom/gzdoom#2413]
### GZDoom version

HEAD

### What Operating System are you using?

Windows 10

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

GetEntryReader calls OpenFile for every call in a non-main thread, this causes OpenFile to fail due to EMFILE (exceeding max open file handles), and it doesn't check for failures either. Memory corruption ensuing from this is a possible cause to #2407

**Comment by prof-hastig** [comment]
The real question should be, why does it open too many files? What code is holding on to the file handles without releasing them?

**Comment by RicardoLuis0** [comment]
it seems to always open a new file unconditionally when it's called from a non-main thread

**Comment by coelckers** [comment]
It does indeed. It's also unavoidable if you don't want to run into race conditions with letting multiple threads read from the same file. Opening multiple files is not the problem here, that's just normal operation.
The actual question to ask here is not why so many files get opened but what happens that they do not get closed again

**Comment by coelckers** [comment]
Duplicate  of #2423
