### ISSUE TITLE
[Patch] Eternal Doom III map compat fixes (100% kills/items)

### ISSUE THREAD

**Issue by JPLeBreton** [ZDoom/gzdoom#2430]
### GZDoom version

git latest

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Linux x86_64

### Is your feature request related to a problem? Please describe.

Attached is a patch (output of `git diff -U0`) with a few level compat fixes for [Eternal Doom III](https://www.doomworld.com/idgames/themes/TeamTNT/eternal/eternal) that enable 100% kills and items. I saw there were already some compat fixes for some levels in GZDoom's data for this WAD; with these additional fixes I was able to get 100% kills + items + secrets on a full run.

[eternal_map_compat_fixes_jpl.patch.txt](https://github.com/ZDoom/gzdoom/files/14477612/eternal_map_compat_fixes_jpl.patch.txt)

**Comment by madame-rachelle** [comment]
[added](https://github.com/ZDoom/gzdoom/commit/9c01738b8662377353db502f35696d4c3e989bb5)

In the future please submit this as a pull request, manual merging is not ideal especially because the diff lacked the headers from the 'case' statements which would have caused problems with the manual merge if the file was ever changed since this submission.
