### ISSUE TITLE
[BUG] Sprite rolling weirdness

### ISSUE THREAD

**Issue by MajorCooke** [ZDoom/gzdoom#2553]
[Test Package](https://drive.google.com/file/d/1gtiF3A2AeYaYNBuufW7A-lR5wnRzdA5m/view?usp=sharing)
`summon rolltest` in console

With the last minute changes to rolling sprites just before 4.12's release, they now have a weird bit of stretching to the top of their sprite at certain degrees but also don't stretch for other axis, making it look very odd.

**Comment by madame-rachelle** [comment]
I don't see any problem, it's rolling just how it's supposed to on my screen.

It may look a bit disorienting because you're used to how it stretched the sprites before, but the math was wrong before because it did not take into account the level's stretch. This rotates it from its "home" position - i.e. if the sprite is not meant to be stretched then it must be accounted for within its ZScript scaling. (XScale 1.2:YScale 1.0 usually does the trick)

In my opinion, the math should *not* be changed back to what it was before. That was horrific how it was previously handled. Check my "fixed" version for proof of what I am talking about, I stretched it on XScale by 1.2 thereby making the pixels square - which fixes the whole thing.

[fixed-rolls.zip](https://github.com/ZDoom/gzdoom/files/15195886/fixed-rolls.zip)
