### ISSUE TITLE
[BUG] MAPINFO ForceTextInMenus causes a menu added in MENUDEF not to appear

### ISSUE THREAD

**Issue by davidxn** [ZDoom/gzdoom#2684]
### GZDoom version

GZDoom 4.12.2

### Which game are you running with GZDoom?

Doom 2

### What Operating System are you using?

Windows 11

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Using the ForceTextInMenus=true property in MAPINFO/GameInfo causes a menu option added via MENUDEF not to appear. Added a ZIP with a demonstration of the behaviour.

[forcetextinmenus.zip](https://github.com/user-attachments/files/16737982/forcetextinmenus.zip)

### Steps to reproduce the behaviour.

See attached ZIP

**Comment by andOlga** [comment]
The source of the issue is that the `ForceTextInMenus` option [effectively replaces](https://github.com/ZDoom/gzdoom/blob/f0ff2736203506b4a0c1502ddbf95ba1766d28ef/src/menu/doommenu.cpp#L158) the `MainMenu` with an entirely *different* menu altogether.

A workaround for this is to add to the replacement menu instead, so `AddListMenu "MainMenu"` becomes `AddListMenu "MainMenuTextOnly"`, which makes the options work again.

I don't think this is an overly major issue since you'd know whether you're using the graphical or the text menu in your mod, but this behavior should probably be documented.

**Comment by Blue-Shadow** [comment]
> I don't think this is an overly major issue since you'd know whether you're using the graphical or the text menu in your mod, but this behavior should probably be documented.

Updated [the documentation](https://zdoom.org/wiki/MAPINFO/GameInfo_definition#ForceTextInMenus).

**Comment by davidxn** [comment]
Thank you! I hadn't anticipated that "force text in menus" would be replacing the entire menu underneath :)
