### ISSUE TITLE
Actors with ROLLSPRITE will be improperly wide

### ISSUE THREAD

**Issue by generic-name-guy** [ZDoom/gzdoom#2759]
## GZDoom version
4.13

## Which game are you running with GZDoom?
Doom II

## Have you checked that no other similar issue already exists?
- [x] I have searched and not found similar issues.

## A clear and concise description of what the bug is.
Actors with ROLLSPRITE are not scaled according to the pixelratio, caused by the commit 7ef6fa9. This causes unintended behaviors such as wide enemies in mods that use the flag in enemies.

## Steps to reproduce the behaviour.
Explain how to reproduce
1. Download a mod with ROLLSPRITE enemies, e.g. Project Brutality;
2. Enter any level with enemies;
3. Look at the enemies, they will be wider.

**Comment by MajorCooke** [comment]
Hmm. Since we have a flag now specifically for it, removing it from ROLLSPRITE could be a possibility now, but also SQUAREPIXELS will need a variant of this for particles and visual thinkers.

**Comment by madame-rachelle** [comment]
The roll sprites have been broken from day 1, it just wasn't noticed until another scaling bug was fixed. Unfortunately a decision had to be made about compatibility, and at some point you have to suck it up and accept that some things will be broken.

GZDoom has always done an exceptional job maintaining compatibility with older content but this is one of those cases where I simply had to draw the line because no matter what every request was somehow going back to the original broken behavior and that is not what I want.

So there will be no more flags added for this - this is how roll sprites are now. If you want a quick cheat to put back the old scaling, this will do the trick: `scale.x = 1.0/(scale.y = sqrt(pixelstretch));` (this sets both scale X and Y). Note that this will elongate the actor and it will still rotate correctly (meaning, if your original art was square/circular it will look odd but it is correct)
